#hipnuc config
imu_serial: "/dev/ttyS2"
baud_rate: 115200
frame_id: "imu_link"
imu_topic: "/imu_raw"

#hipnuc data package 
frame_id_costom: "base_link_hipnuc"
imu_topic_costom: "/imu_package_hipnuc"

